#ifndef FAKE_TIMETAG_DEVICE_PLUGIN_GLOBAL_H
#define FAKE_TIMETAG_DEVICE_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FAKE_TIMETAG_DEVICE_PLUGIN_LIBRARY)
#  define FAKE_TIMETAG_DEVICE_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FAKE_TIMETAG_DEVICE_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FAKE_TIMETAG_DEVICE_PLUGIN_GLOBAL_H
