#ifndef TIMETRACE_VIEW_PLUGIN_GLOBAL_H
#define TIMETRACE_VIEW_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CORRELATION_VIEW_PLUGIN_LIBRARY)
#  define CORRELATION_VIEW_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CORRELATION_VIEW_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TIMETRACE_VIEW_PLUGIN_GLOBAL_H
